export const overlayCopy = {
    fr: {
        title: 'Overlay en partie', enable: 'Activer le panneau en partie',
        description: 'Un panneau passif affiche les informations de votre personnage. Il laisse passer les clics vers le jeu.',
        exclusive: 'Je joue en plein écran exclusif', exclusiveHint: 'Le plein écran exclusif masque l’overlay. Utilisez le mode fenêtré ou sans bordure pour l’afficher.',
        shortcut: 'Ctrl + Alt + O : activer ou désactiver l’overlay.', monitor: 'Écran de l’aperçu',
        positionHint: 'En partie, la position et la largeur sont relatives à la fenêtre de LoL. Hors partie, l’aperçu utilise l’écran choisi. Si la fenêtre du jeu est introuvable, le panneau reste masqué.',
        x: 'Depuis la gauche (%)', y: 'Depuis le haut (%)', width: 'Largeur (%)', opacity: 'Opacité (%)',
        save: 'Enregistrer', saving: 'Enregistrement…', preview: 'Aperçu pendant 30 secondes', stopPreview: 'Arrêter l’aperçu',
        previewHint: 'Enregistrez vos réglages pour les appliquer à l’aperçu.', saved: 'Réglages enregistrés.',
        invalid: 'Vérifiez les valeurs : le panneau doit rester dans la fenêtre, notamment position gauche + largeur ≤ 100 %.',
        failed: 'Impossible d’appliquer les réglages. Vérifiez l’écran choisi puis réessayez.', storage: 'Impossible de conserver les réglages sur cet ordinateur.',
        unavailable: 'Overlay indisponible sur cet écran ou dans ce mode.', disabled: 'Désactivé', visible: 'Affiché', hidden: 'En attente d’une fenêtre de jeu compatible',
        desktop: 'Ouvrez l’application desktop pour régler et tester l’overlay.', loading: 'Chargement des réglages…',
        previewTitle: 'Aperçu de l’overlay', previewBody: 'Aucune partie simulée. Vos informations apparaîtront ici lorsque LoL les rendra disponibles.',
    },
    en: {
        title: 'In-game overlay', enable: 'Enable the in-game panel',
        description: 'A passive panel shows your character’s information. Clicks pass through to the game.',
        exclusive: 'I play in exclusive fullscreen', exclusiveHint: 'Exclusive fullscreen hides the overlay. Use windowed or borderless mode to show it.',
        shortcut: 'Ctrl + Alt + O: enable or disable the overlay.', monitor: 'Preview monitor',
        positionHint: 'In game, position and width are relative to the LoL window. Outside a game, the preview uses the selected monitor. If the game window cannot be found, the panel stays hidden.',
        x: 'From the left (%)', y: 'From the top (%)', width: 'Width (%)', opacity: 'Opacity (%)',
        save: 'Save', saving: 'Saving…', preview: 'Preview for 30 seconds', stopPreview: 'Stop preview',
        previewHint: 'Save your settings to apply them to the preview.', saved: 'Settings saved.',
        invalid: 'Check the values: the panel must remain inside the window, including left position + width ≤ 100%.',
        failed: 'Could not apply settings. Check the selected monitor and try again.', storage: 'Could not save settings on this computer.',
        unavailable: 'Overlay unavailable on this monitor or in this mode.', disabled: 'Disabled', visible: 'Visible', hidden: 'Waiting for a compatible game window',
        desktop: 'Open the desktop app to configure and test the overlay.', loading: 'Loading settings…',
        previewTitle: 'Overlay preview', previewBody: 'No simulated game. Your information will appear here when LoL makes it available.',
    },
} as const;
