export const buildCopy={
 fr:{
  prepick:'Votre prépick',lockedPick:'Votre pick',title:'Préparation',community:'Communauté',equipped:'Runes équipées',catalog:'Catalogue',champion:'Champion à consulter',choose:'Choisir un champion',follow:'Suivre mon champion',following:'Votre champion',manual:'Consultation',filters:'Filtres statistiques',region:'Région',queue:'File',role:'Poste',rank:'Rang',all:'Tous les rangs',patch:'Patch',refresh:'Actualiser les statistiques',
  loading:'Chargement des statistiques…',selectFirst:'Choisissez un champion ou préparez votre pick dans LoL.',empty:'Pas encore de données pour ce champion et ces filtres.',runes:'Runes observées',selected:'Variante consultée',returnVariant:'Revenir à la variante',runeMissing:'Aucune page de runes exploitable pour ce patch.',
  items:'Objets & achats',purchase_order:'Ordre des achats',final_items:'Inventaire final',item:'Objets fréquents',trinket:'Reliques',skill_order:'Compétences',summoner_spells:'Sorts d’invocateur',
  emptySelection:'Aucun objet observé dans cette variante.',sequence:'Séquence observée',alternative:'Variante',games:'parties',frequency:'Fréquence',winrate:'Victoire',sample:'Échantillon insuffisant',categoryMissing:'Pas de données pour cette catégorie.',unknown:'Indisponible dans ce catalogue',
  purchaseHint:'Achats chronologiques, composants et consommables compris.',finalHint:'Présents en fin de partie ; aucun ordre d’achat.',itemHint:'Présence en fin de partie, pas une suggestion situationnelle.',skillHint:'Points investis, pas niveaux du champion. Séquence parfois incomplète.',spellHint:'Ordre D/F le plus fréquent parmi les parties observées ; la position de Flash reste la vôtre.',
  source:'Source & méthode',sourceTitle:'Statistiques communautaires',sourceHint:'Chaque catégorie est calculée séparément. Les combinaisons affichées ensemble n’ont pas de taux de victoire commun.',collected:'Données au',published:'Publication',threshold:'Seuil des taux',scope:'Population',sources:'Source : API Open LoL Companion',independent:'Catégories indépendantes',close:'Fermer',retry:'Réessayer',
  roles:{TOP:'Top',JUNGLE:'Jungle',MIDDLE:'Mid',BOTTOM:'Bot',UTILITY:'Support',UNKNOWN:'Poste inconnu'},
  queues:{420:'Solo/Duo',440:'Flex',400:'Normal Draft',490:'Partie rapide'},
  errors:{not_configured:'Les statistiques ne sont pas encore connectées sur cet appareil.',invalid_configuration:'La connexion aux statistiques doit être configurée.',invalid_request:'Ces filtres ne sont pas pris en charge.',unauthorized:'L’accès aux statistiques a expiré ou n’est pas autorisé.',unavailable:'Les statistiques sont temporairement indisponibles.',rate_limited:'Le service est occupé. Réessayez dans un instant.',invalid_response:'Ces données ne peuvent pas être affichées de façon fiable.',changed_snapshot:'Les statistiques ont changé pendant le chargement. Actualisez.',desktop_required:'Les statistiques sont accessibles dans l’application desktop.'},
 },
 en:{
  prepick:'Your pre-pick',lockedPick:'Your pick',title:'Preparation',community:'Community',equipped:'Equipped runes',catalog:'Catalog',champion:'Champion to browse',choose:'Choose a champion',follow:'Follow my champion',following:'Your champion',manual:'Browsing',filters:'Statistics filters',region:'Region',queue:'Queue',role:'Role',rank:'Rank',all:'All ranks',patch:'Patch',refresh:'Refresh statistics',
  loading:'Loading statistics…',selectFirst:'Choose a champion or prepare your pick in LoL.',empty:'No data yet for this champion and these filters.',runes:'Observed runes',selected:'Previewed variant',returnVariant:'Return to variant',runeMissing:'No usable rune page for this patch.',
  items:'Items & purchases',purchase_order:'Purchase order',final_items:'Final inventory',item:'Frequent items',trinket:'Trinkets',skill_order:'Abilities',summoner_spells:'Summoner spells',
  emptySelection:'No items observed in this variant.',sequence:'Observed sequence',alternative:'Variant',games:'games',frequency:'Frequency',winrate:'Win rate',sample:'Insufficient sample',categoryMissing:'No data for this category.',unknown:'Unavailable in this catalog',
  purchaseHint:'Chronological purchases, including components and consumables.',finalHint:'Present at game end; not a purchase order.',itemHint:'Present at game end; not a situational recommendation.',skillHint:'Points invested, not champion levels. Sequences may be incomplete.',spellHint:'Most frequent D/F order among observed games; your own Flash position is kept.',
  source:'Source & method',sourceTitle:'Community statistics',sourceHint:'Each category is calculated separately. Combinations shown together have no shared win rate.',collected:'Data as of',published:'Published',threshold:'Rate threshold',scope:'Population',sources:'Source: Open LoL Companion API',independent:'Independent categories',close:'Close',retry:'Retry',
  roles:{TOP:'Top',JUNGLE:'Jungle',MIDDLE:'Mid',BOTTOM:'Bot',UTILITY:'Support',UNKNOWN:'Unknown role'},
  queues:{420:'Solo/Duo',440:'Flex',400:'Normal Draft',490:'Quickplay'},
  errors:{not_configured:'Statistics are not connected on this device yet.',invalid_configuration:'The statistics connection needs configuration.',invalid_request:'These filters are not supported.',unauthorized:'Statistics access has expired or is not authorized.',unavailable:'Statistics are temporarily unavailable.',rate_limited:'The service is busy. Try again shortly.',invalid_response:'These data cannot be displayed reliably.',changed_snapshot:'Statistics changed while loading. Refresh to try again.',desktop_required:'Statistics are available in the desktop application.'},
 },
} as const;
