export const buildCopy={
 fr:{
  otherCategory:'Autre catégorie',variantCap:'Plafond de variantes par catégorie',
  observationCategories:{starter:'Objets de départ',boots:'Bottes',core:'Trois premiers objets',item_slot_4:'Quatrième objet',item_slot_5:'Cinquième objet',item_slot_6:'Sixième objet',rune_keystone:'Clé de voûte',rune_primary_style:'Arbre principal',rune_secondary_style:'Arbre secondaire',rune_secondary_pair:'Paire secondaire',rune_slot_1:'Runes — premier emplacement',rune_slot_2:'Runes — deuxième emplacement',rune_slot_3:'Runes — troisième emplacement',rune_shard_offense:'Fragment offensif',rune_shard_flex:'Fragment adaptatif',rune_shard_defense:'Fragment défensif',skill_start:'Trois premiers points',skill_priority:'Priorité des compétences',special_skill_order:'Évolutions des compétences'},

  championSummary:'Résumé du champion',championPickRate:'Présence dans les parties',skillTimings:'Temps des points investis',skillTimingsHint:'Rang du point investi, pas le niveau du champion. Temps moyen observé et effectif propres à chaque sort.',skillPoint:'Point',meanTime:'Temps moyen',itemTimings:'Événements d’objets par minute',itemTimingsHint:'Comptes d’événements, pas de parties distinctes. Fréquences observées, sans heure d’achat recommandée ni médiane d’achèvement.',observedItem:'Objet observé',eventType:'Événement',otherEvent:'Autre événement',minuteBucket:'Minute de partie',events:'Événements',eventCap:'Plafond de lignes du groupe',eventsOmitted:'Lignes non servies',eventCapBias:'Le plafond conserve les événements les plus fréquents : les ventes et autres actions rares peuvent manquer. Une absence ne signifie pas zéro événement.',omittedVariants:'Variantes non publiées',omittedVariantsHint:'Compte propre à ce champion, ce rôle, ce rang et cette catégorie ; jamais le total global de la collecte.',previous:'Précédent',next:'Suivant',
  itemEventNames:{ITEM_PURCHASED:'Achat',ITEM_SOLD:'Vente',ITEM_DESTROYED:'Consommation / destruction',ITEM_UNDO_REMOVE:'Achat annulé',ITEM_UNDO_RESTORE:'Vente annulée'},

  rankTiers:['Fer','Bronze','Argent','Or','Platine','Émeraude','Diamant','Maître','Grand maître','Challenger'],
  populationNeutral:'Population statistique',populationBias:'Échantillon surtout Master+',populationScope:'Répartition du périmètre patch / région / file, tous rôles confondus ; pas celle du poste sélectionné.',populationMissing:'Répartition non disponible dans cet instantané.',apexShare:'Part Master+',participations:'Participations',share:'Part',total:'Total',unrankedMode:'Mode non classé',unranked:'Sans classement',

  chooseRole:'Choisissez le poste à consulter.',matchupChosen:'Matchup choisi',matchupUnavailable:'Données de matchup indisponibles : statistiques générales du champion affichées.',clearMatchup:'Retirer le matchup',
  prepick:'Votre prépick',lockedPick:'Votre pick',title:'Préparation',community:'Communauté',equipped:'Runes équipées',catalog:'Catalogue',champion:'Champion à consulter',choose:'Choisir un champion',follow:'Suivre mon champion',following:'Votre champion',manual:'Consultation',filters:'Filtres statistiques',region:'Région',queue:'File',role:'Poste',rank:'Rang',all:'Échantillon collecté',patch:'Patch',refresh:'Actualiser les statistiques',
  loading:'Chargement des statistiques…',selectFirst:'Choisissez un champion ou préparez votre pick dans LoL.',empty:'Pas encore de données pour ce champion et ces filtres.',runes:'Runes observées',selected:'Variante consultée',returnVariant:'Revenir à la variante',runeMissing:'Aucune page de runes exploitable pour ce patch.',
  items:'Objets & achats',purchase_order:'Ordre des achats',final_items:'Inventaire final',item:'Objets fréquents',trinket:'Reliques',skill_order:'Compétences',summoner_spells:'Sorts d’invocateur',
  emptySelection:'Aucun objet observé dans cette variante.',sequence:'Séquence observée',alternative:'Variante',games:'parties',frequency:'Fréquence',winrate:'Victoire',sample:'Échantillon insuffisant',categoryMissing:'Pas de données pour cette catégorie.',unknown:'Indisponible dans ce catalogue',
  purchaseHint:'Achats chronologiques, composants et consommables compris.',finalHint:'Présents en fin de partie ; aucun ordre d’achat.',itemHint:'Présence en fin de partie, pas une suggestion situationnelle.',skillHint:'Points investis, pas niveaux du champion. Séquence parfois incomplète.',spellHint:'Ordre D/F le plus fréquent parmi les parties observées ; la position de Flash reste la vôtre.',
  source:'Source & méthode',sourceTitle:'Statistiques communautaires',sourceHint:'Chaque catégorie est calculée séparément. Les combinaisons affichées ensemble n’ont pas de taux de victoire commun.',collected:'Données au',published:'Publication',threshold:'Seuil des taux',scope:'Population',sources:'Source : API Open LoL Companion',independent:'Catégories indépendantes',close:'Fermer',retry:'Réessayer',
  roles:{TOP:'Top',JUNGLE:'Jungle',MIDDLE:'Mid',BOTTOM:'Bot',UTILITY:'Support',UNKNOWN:'Poste inconnu'},
  queues:{420:'Solo/Duo',440:'Flex',400:'Normal Draft',490:'Partie rapide'},
  errors:{not_configured:'Les statistiques ne sont pas encore connectées sur cet appareil.',invalid_configuration:'La connexion aux statistiques doit être configurée.',invalid_request:'Ces filtres ne sont pas pris en charge.',unauthorized:'L’accès aux statistiques a expiré ou n’est pas autorisé.',unavailable:'Les statistiques sont temporairement indisponibles.',rate_limited:'Le service est occupé. Réessayez dans un instant.',invalid_response:'Ces données ne peuvent pas être affichées de façon fiable.',changed_snapshot:'Les statistiques ont changé pendant le chargement. Actualisez.',desktop_required:'Les statistiques sont accessibles dans l’application desktop.'},
 },
 en:{
  otherCategory:'Other category',variantCap:'Variant limit per category',
  observationCategories:{starter:'Starting items',boots:'Boots',core:'First three items',item_slot_4:'Fourth item',item_slot_5:'Fifth item',item_slot_6:'Sixth item',rune_keystone:'Keystone',rune_primary_style:'Primary tree',rune_secondary_style:'Secondary tree',rune_secondary_pair:'Secondary pair',rune_slot_1:'Runes — first slot',rune_slot_2:'Runes — second slot',rune_slot_3:'Runes — third slot',rune_shard_offense:'Offensive shard',rune_shard_flex:'Adaptive shard',rune_shard_defense:'Defensive shard',skill_start:'First three points',skill_priority:'Ability priority',special_skill_order:'Ability evolutions'},

  championSummary:'Champion summary',championPickRate:'Match presence',skillTimings:'Skill point timings',skillTimingsHint:'Order of points invested, not the champion level. Observed mean time and sample size for each ability.',skillPoint:'Point',meanTime:'Mean time',itemTimings:'Item events by minute',itemTimingsHint:'Event counts, not distinct matches. Observed frequencies, without recommended purchase time or median completion time.',observedItem:'Observed item',eventType:'Event',otherEvent:'Other event',minuteBucket:'Game minute',events:'Events',eventCap:'Group row limit',eventsOmitted:'Rows not served',eventCapBias:'The limit retains the most frequent events: sales and other rare actions may be missing. Missing does not mean zero events.',omittedVariants:'Unpublished variants',omittedVariantsHint:'Count for this champion, role, rank and category only; never the global collection total.',previous:'Previous',next:'Next',
  itemEventNames:{ITEM_PURCHASED:'Purchase',ITEM_SOLD:'Sale',ITEM_DESTROYED:'Consumption / destruction',ITEM_UNDO_REMOVE:'Purchase undone',ITEM_UNDO_RESTORE:'Sale undone'},

  rankTiers:['Iron','Bronze','Silver','Gold','Platinum','Emerald','Diamond','Master','Grandmaster','Challenger'],
  populationNeutral:'Statistical population',populationBias:'Mostly Master+ sample',populationScope:'Distribution for patch / region / queue, all roles combined; not the selected role.',populationMissing:'Distribution unavailable in this snapshot.',apexShare:'Master+ share',participations:'Participations',share:'Share',total:'Total',unrankedMode:'Unranked mode',unranked:'Unranked',

  chooseRole:'Choose the role to browse.',matchupChosen:'Selected matchup',matchupUnavailable:'Matchup data unavailable: showing general champion statistics.',clearMatchup:'Clear matchup',
  prepick:'Your pre-pick',lockedPick:'Your pick',title:'Preparation',community:'Community',equipped:'Equipped runes',catalog:'Catalog',champion:'Champion to browse',choose:'Choose a champion',follow:'Follow my champion',following:'Your champion',manual:'Browsing',filters:'Statistics filters',region:'Region',queue:'Queue',role:'Role',rank:'Rank',all:'Collected sample',patch:'Patch',refresh:'Refresh statistics',
  loading:'Loading statistics…',selectFirst:'Choose a champion or prepare your pick in LoL.',empty:'No data yet for this champion and these filters.',runes:'Observed runes',selected:'Previewed variant',returnVariant:'Return to variant',runeMissing:'No usable rune page for this patch.',
  items:'Items & purchases',purchase_order:'Purchase order',final_items:'Final inventory',item:'Frequent items',trinket:'Trinkets',skill_order:'Abilities',summoner_spells:'Summoner spells',
  emptySelection:'No items observed in this variant.',sequence:'Observed sequence',alternative:'Variant',games:'games',frequency:'Frequency',winrate:'Win rate',sample:'Insufficient sample',categoryMissing:'No data for this category.',unknown:'Unavailable in this catalog',
  purchaseHint:'Chronological purchases, including components and consumables.',finalHint:'Present at game end; not a purchase order.',itemHint:'Present at game end; not a situational recommendation.',skillHint:'Points invested, not champion levels. Sequences may be incomplete.',spellHint:'Most frequent D/F order among observed games; your own Flash position is kept.',
  source:'Source & method',sourceTitle:'Community statistics',sourceHint:'Each category is calculated separately. Combinations shown together have no shared win rate.',collected:'Data as of',published:'Published',threshold:'Rate threshold',scope:'Population',sources:'Source: Open LoL Companion API',independent:'Independent categories',close:'Close',retry:'Retry',
  roles:{TOP:'Top',JUNGLE:'Jungle',MIDDLE:'Mid',BOTTOM:'Bot',UTILITY:'Support',UNKNOWN:'Unknown role'},
  queues:{420:'Solo/Duo',440:'Flex',400:'Normal Draft',490:'Quickplay'},
  errors:{not_configured:'Statistics are not connected on this device yet.',invalid_configuration:'The statistics connection needs configuration.',invalid_request:'These filters are not supported.',unauthorized:'Statistics access has expired or is not authorized.',unavailable:'Statistics are temporarily unavailable.',rate_limited:'The service is busy. Try again shortly.',invalid_response:'These data cannot be displayed reliably.',changed_snapshot:'Statistics changed while loading. Refresh to try again.',desktop_required:'Statistics are available in the desktop application.'},
 },
} as const;
