const fr = {
    navigation: { champions:'Champions', dashboard: 'Accueil', 'champ-select': 'Draft', 'in-game': 'Partie', 'post-game': 'Bilan', settings: 'Réglages' },
    shell: { brand: 'OPEN LOL', menu: 'Toutes les pages', close: 'Fermer', back: 'Retour', search: 'Rechercher une page', nothing: 'Aucune page trouvée', navigation: 'Navigation principale', settings: 'Réglages', theme: 'Changer de thème', current: 'Revenir à la session', legal: "Open LoL Companion n'est pas approuvé par Riot Games et ne reflète pas ses opinions. League of Legends et ses marques appartiennent à Riot Games." },
    connection: { browser: 'Aperçu navigateur', browserHint: "La connexion à League est disponible dans l’application desktop.", waiting: 'En attente du client', waitingHint: 'Ouvrez League of Legends. La connexion et le suivi de partie sont automatiques.', connected: 'Client connecté', connectedHint: 'Votre session est suivie. L’interface changera au début de la draft.', error: 'Connexion indisponible', errorHint: 'Le suivi du client ne répond pas. Vous pouvez réessayer.', retry: 'Réessayer', checking: 'Connexion en cours', checkingHint: 'Recherche du client League of Legends…', offline: 'Client déconnecté', data: 'Données non disponibles', phase: 'Session actuelle' },
    home: { eyebrow: 'VOTRE ESPACE DE JEU', title: 'Prêt pour la prochaine.', description: 'Votre session, votre préparation et votre progression, au même endroit.', profile: 'Votre profil', profileHint: 'Le profil et les comptes seront disponibles après leur raccordement au client.', history: 'Dernières parties', historyHint: 'L’historique n’est pas encore relié à votre compte.', friends: 'Amis & joueurs suivis', friendsHint: 'Les parties de vos amis apparaîtront ici une fois ce service connecté.', progress: 'À travailler', progressHint: 'Les conseils personnalisés attendent vos données de partie.', openDraft: 'Ouvrir la draft', empty: 'Aucune donnée chargée' },
    game: { draftHint: 'Rejoignez une sélection dans League pour afficher les picks et bans.', blue: 'Équipe bleue', red: 'Équipe rouge', slot: 'Emplacement', waiting: 'En attente', runes: 'Runes & préparation', runesHint: 'Aucune page de runes disponible pour cette session.', items: 'Parcours d’objets', itemsHint: 'Aucun build disponible. Aucun import ne sera effectué.', suggestions: 'Suggestions', suggestionsHint: 'Les recommandations ne sont pas encore connectées.', liveHint: 'Les informations en partie attendent le raccordement des données de jeu.', postHint: 'Le bilan sera disponible après réception des statistiques de la partie.', unavailable: 'En attente des données', phaseUnknown: 'Phase indisponible' },
    settings: { title: 'À votre façon.', hint: 'Vos préférences s’appliquent immédiatement.', appearance: 'Apparence', dark: 'Sombre', light: 'Clair', language: 'Langue', motion: 'Animations', motionHint: 'Transitions légères entre les pages et à l’arrivée des panneaux.', reduced: 'Votre système demande de réduire les animations.', saved: 'Préférences enregistrées sur cet appareil.', storage: 'Vos préférences ne peuvent pas être enregistrées sur cet appareil.', general: 'INTERFACE' },
    draft:{browse:'Consulter la préparation',inspected:'Champion consulté',allies:'Votre équipe',enemies:'Équipe adverse',sideUnknown:'Côté en attente',prepick:'Présélection',locked:'Verrouillé',you:'Vous',bans:'Bans',timer:'Temps restant',unknown:'Champion indisponible',readOnly:'Sélection suivie en direct · vos actions restent dans League',unsupported:'Ce mode de sélection n’est pas encore pris en charge.',roles:{top:'Top',jungle:'Jungle',middle:'Mid',bottom:'Bot',utility:'Support'}},
    phases: { None: 'Hors partie', Lobby: 'Salon', Matchmaking: 'Recherche de partie', CheckedIntoTournament: 'Tournoi', ReadyCheck: 'Partie trouvée', ChampSelect: 'Sélection des champions', GameStart: 'Chargement de la partie', FailedToLaunch: 'Démarrage impossible', InProgress: 'En partie', Reconnect: 'Reconnexion à la partie', WaitingForStats: 'Statistiques en cours', PreEndOfGame: 'Fin de partie', EndOfGame: 'Après-partie', TerminatedInError: 'Partie interrompue', Unknown: 'Phase inconnue' }
};
const en: typeof fr = {
    navigation: { champions:'Champions', dashboard: 'Home', 'champ-select': 'Draft', 'in-game': 'Match', 'post-game': 'Summary', settings: 'Settings' },
    shell: { brand: 'OPEN LOL', menu: 'All pages', close: 'Close', back: 'Back', search: 'Find a page', nothing: 'No pages found', navigation: 'Main navigation', settings: 'Settings', theme: 'Switch theme', current: 'Back to current session', legal: 'Open LoL Companion is not endorsed by Riot Games and does not reflect its views. League of Legends and its trademarks belong to Riot Games.' },
    connection: { browser: 'Browser preview', browserHint: 'Connect to League through the desktop application.', waiting: 'Waiting for the client', waitingHint: 'Open League of Legends. Connection and session tracking are automatic.', connected: 'Client connected', connectedHint: 'Your session is tracked. The interface will switch when draft starts.', error: 'Connection unavailable', errorHint: 'Client tracking is not responding. You can try again.', retry: 'Try again', checking: 'Connecting', checkingHint: 'Looking for the League of Legends client…', offline: 'Client disconnected', data: 'Data unavailable', phase: 'Current session' },
    home: { eyebrow: 'YOUR PLAY SPACE', title: 'Ready for the next one.', description: 'Your session, preparation and progress, in one place.', profile: 'Your profile', profileHint: 'Your profile and accounts will be available once connected to the client.', history: 'Recent matches', historyHint: 'Match history is not connected to your account yet.', friends: 'Friends & followed players', friendsHint: 'Your friends’ matches will appear here once this service is connected.', progress: 'Work on', progressHint: 'Personal advice is waiting for your match data.', openDraft: 'Open draft', empty: 'No data loaded' },
    game: { draftHint: 'Join champion select in League to display picks and bans.', blue: 'Blue team', red: 'Red team', slot: 'Slot', waiting: 'Waiting', runes: 'Runes & preparation', runesHint: 'No rune page is available for this session.', items: 'Item path', itemsHint: 'No build available. No import will be performed.', suggestions: 'Suggestions', suggestionsHint: 'Recommendations are not connected yet.', liveHint: 'Live match information is waiting for game data to be connected.', postHint: 'The summary will be available once match statistics are received.', unavailable: 'Waiting for data', phaseUnknown: 'Phase unavailable' },
    settings: { title: 'Make it yours.', hint: 'Your preferences apply immediately.', appearance: 'Appearance', dark: 'Dark', light: 'Light', language: 'Language', motion: 'Animations', motionHint: 'Subtle transitions between pages and when panels appear.', reduced: 'Your system requests reduced motion.', saved: 'Preferences saved on this device.', storage: 'Your preferences cannot be saved on this device.', general: 'INTERFACE' },
    draft:{browse:'Browse preparation',inspected:'Previewed champion',allies:'Your team',enemies:'Opponents',sideUnknown:'Side pending',prepick:'Preselection',locked:'Locked',you:'You',bans:'Bans',timer:'Time remaining',unknown:'Champion unavailable',readOnly:'Live champion select · choose in League',unsupported:'This champion select mode is not supported yet.',roles:{top:'Top',jungle:'Jungle',middle:'Mid',bottom:'Bot',utility:'Support'}},
    phases: { None: 'Out of game', Lobby: 'Lobby', Matchmaking: 'Matchmaking', CheckedIntoTournament: 'Tournament', ReadyCheck: 'Match found', ChampSelect: 'Champion select', GameStart: 'Loading match', FailedToLaunch: 'Failed to launch', InProgress: 'In game', Reconnect: 'Reconnecting to match', WaitingForStats: 'Waiting for stats', PreEndOfGame: 'Match ending', EndOfGame: 'Post game', TerminatedInError: 'Match interrupted', Unknown: 'Unknown phase' }
};
export const copy = { fr, en };
export type Copy = typeof fr;
