const fr={
 sourceLocal:'Source : client LoL',sourceApi:'Source : API publique',localHistory:'Historique fourni par le client LoL : il peut être incomplet.',localEmpty:'Le client ne fournit aucune partie actuellement.',localEnd:'Fin des parties fournies par le client',custom:'Personnalisée',localOmitted:'Certaines parties du client sont incomplètes et ne peuvent pas être affichées.',
 active:'Compte actif dans League',disconnected:'League déconnecté · compte conservé',unknownAccount:'Compte League indisponible · dernier compte affiché',waitingAccount:'En attente du compte League',followsClient:'L’accueil suit le compte connecté dans League.',
 title:'Joueurs',global:'Joueur, champion, page…',riotId:'Riot ID',placeholder:'Nom du joueur#TAG',region:'Région',search:'Rechercher',findPlayer:'Rechercher un joueur',hint:'Un Riot ID actuel et sa région suffisent.',invalid:'Saisissez un Riot ID complet : nom#TAG.',
 loading:'Recherche du joueur…',loadingMatches:'Chargement des parties…',retry:'Réessayer',refresh:'Actualiser',level:'Niveau',home:'Compte de l’accueil',pin:'Utiliser pour l’accueil',pinned:'Affiché à l’accueil',forget:'Retirer de l’accueil',change:'Changer de compte',view:'Voir le profil',local:'Favori local · ne vérifie pas la propriété du compte',storage:'Choix conservé pour cette session uniquement : stockage local indisponible.',
 noHome:'Votre compte, à portée de main.',choose:'Choisir le compte de l’accueil',noHomeHint:'Retrouvez votre profil et vos dernières parties, même quand League est fermé.',
 history:'Dernières parties',empty:'Aucune partie publique sur cette page.',more:'Afficher plus de parties',end:'Fin de l’historique disponible',omitted:'Certaines parties ne sont pas publiables ou appartiennent à une autre région.',win:'Victoire',loss:'Défaite',champion:'Champion',openChampion:'Voir le champion',unknownChampion:'Champion indisponible dans le catalogue local',kda:'Éliminations / morts / assistances',duration:'Durée',mode:'Mode',solo:'Solo / Duo',flex:'Flex',aram:'ARAM',unranked:'Non classé',rankUnavailable:'Rang indisponible',fetched:'Données du',recent:'Sur les parties affichées',wins:'victoires',lp:'PL',
 tiers:{IRON:'Fer',BRONZE:'Bronze',SILVER:'Argent',GOLD:'Or',PLATINUM:'Platine',EMERALD:'Émeraude',DIAMOND:'Diamant',MASTER:'Maître',GRANDMASTER:'Grand maître',CHALLENGER:'Challenger'},
 errors:{not_configured:'Le service de profils n’est pas encore configuré dans cette installation.',invalid_configuration:'La configuration du service de profils est invalide.',invalid_request:'Vérifiez le Riot ID et la région.',unauthorized:'L’accès au service de profils n’est pas autorisé.',not_found:'Ce Riot ID est introuvable dans cette région.',unavailable:'Le service de profils ne répond pas. Réessayez plus tard.',rate_limited:'Le service reçoit trop de demandes. Réessayez dans un moment.',invalid_response:'Les données reçues sont incohérentes. Elles n’ont pas été affichées.',desktop_required:'Les profils se chargent dans l’application desktop. Cet aperçu navigateur ne dispose pas du transport natif.'},
};
const en:typeof fr={
 sourceLocal:'Source: League client',sourceApi:'Source: public API',localHistory:'History provided by the League client: it may be incomplete.',localEmpty:'The client is not providing any matches right now.',localEnd:'End of matches provided by the client',custom:'Custom game',localOmitted:'Some client matches are incomplete and cannot be displayed.',
 active:'Active League account',disconnected:'League disconnected · account kept',unknownAccount:'League account unavailable · showing last account',waitingAccount:'Waiting for League account',followsClient:'Home follows the account connected in League.',
 title:'Players',global:'Player, champion, page…',riotId:'Riot ID',placeholder:'Player name#TAG',region:'Region',search:'Search',findPlayer:'Find a player',hint:'Use a current Riot ID and its region.',invalid:'Enter a complete Riot ID: name#TAG.',
 loading:'Finding player…',loadingMatches:'Loading matches…',retry:'Try again',refresh:'Refresh',level:'Level',home:'Home account',pin:'Use on home',pinned:'Shown on home',forget:'Remove from home',change:'Change account',view:'View profile',local:'Local favorite · does not verify account ownership',storage:'Saved for this session only: local storage unavailable.',
 noHome:'Your account, within reach.',choose:'Choose your home account',noHomeHint:'Keep your profile and recent matches nearby, even when League is closed.',
 history:'Recent matches',empty:'No public matches on this page.',more:'Load more matches',end:'End of available history',omitted:'Some matches cannot be published or belong to another region.',win:'Victory',loss:'Defeat',champion:'Champion',openChampion:'View champion',unknownChampion:'Champion unavailable in the local catalog',kda:'Kills / deaths / assists',duration:'Duration',mode:'Mode',solo:'Solo / Duo',flex:'Flex',aram:'ARAM',unranked:'Unranked',rankUnavailable:'Rank unavailable',fetched:'Data as of',recent:'Among displayed matches',wins:'wins',lp:'LP',
 tiers:{IRON:'Iron',BRONZE:'Bronze',SILVER:'Silver',GOLD:'Gold',PLATINUM:'Platinum',EMERALD:'Emerald',DIAMOND:'Diamond',MASTER:'Master',GRANDMASTER:'Grandmaster',CHALLENGER:'Challenger'},
 errors:{not_configured:'The profile service is not configured in this installation yet.',invalid_configuration:'The profile service configuration is invalid.',invalid_request:'Check the Riot ID and region.',unauthorized:'Access to the profile service is not authorized.',not_found:'This Riot ID was not found in this region.',unavailable:'The profile service is not responding. Try again later.',rate_limited:'The service is receiving too many requests. Try again shortly.',invalid_response:'The received data is inconsistent and was not displayed.',desktop_required:'Profiles load in the desktop application. This browser preview has no native transport.'},
};
export const playersCopy={fr,en};
