const fr={
 title:'Vos réglages, au bon endroit.',intro:'Trouvez une option et ajustez-la directement.',search:'Rechercher un réglage',placeholder:'Thème, moins d’animations, Flash sur F…',clear:'Effacer la recherche',categories:'Catégories de réglages',all:'Tous',app:'Application',league:'League of Legends',result:'réglage',results:'réglages',recent:'Modifié récemment',
 empty:'Aucun réglage trouvé.',emptyHint:'Essayez « langue », « animations » ou « Flash ».',showAll:'Voir tous les réglages',dark:'Sombre',light:'Clair',enabled:'Activées',disabled:'Désactivées',unset:'À choisir',undo:'Annuler',undoLabel:'Annuler la dernière modification',changed:'Dernière modification',saved:'Réglages enregistrés sur cet appareil.',storage:'Modifications conservées pour cette session. La sauvegarde locale a échoué.',retry:'Réessayer la sauvegarde',reduced:'Votre système réduit les animations : ce choix reste prioritaire.',
 nativeEnabled:'Activé',nativeDisabled:'Désactivé',unknown:'État inconnu',desktopOnly:'Disponible dans l’application desktop.',trayUnavailable:'La barre système est indisponible. Fermer quitte l’application.',nativeUnknown:'Le démarrage automatique n’a pas pu être lu.',nativePending:'Vérification du réglage…',nativeFailed:'Le réglage système n’a pas pu être confirmé.',nativeStorage:'Les préférences système n’ont pas pu être lues. Modifiez le comportement de fermeture pour les réenregistrer.',localeFailed:'La langue du menu système n’a pas pu être synchronisée.',nativeRetry:'Relire les réglages système',localeRetry:'Synchroniser le menu',
 names:{autoRunes:'Importer les runes',autoItems:'Importer les objets',autoMinGames:'Minimum de parties',autoCustomRole:'Poste en personnalisée',closeToTray:'Fermer en arrière-plan',autostartEnabled:'Lancer à la connexion',theme:'Thème',locale:'Langue',motion:'Animations',flashSlot:'Position de Flash'},
 paths:{autoRunes:'League / Imports',autoItems:'League / Imports',autoMinGames:'League / Imports',autoCustomRole:'League / Imports',closeToTray:'Application / Fenêtre',autostartEnabled:'Application / Démarrage',theme:'Application / Apparence',locale:'Application / Langue',motion:'Application / Accessibilité',flashSlot:'League / Préparation'},
 descriptions:{autoRunes:'Au prépick, importe la page la plus jouée au poste choisi.',autoItems:'Au prépick, importe le set le plus joué au poste choisi.',autoMinGames:'Nombre de parties requis pour importer une variante.',autoCustomRole:'Poste utilisé quand League ne l’indique pas en personnalisée.',closeToTray:'Garde le compagnon actif. Quitter reste accessible dans le menu système.',autostartEnabled:'Lance le compagnon à l’ouverture de votre session.',theme:'Sombre ou clair, selon votre confort.',locale:'Les textes de l’application changent immédiatement.',motion:'Transitions et mouvements du compagnon.',flashSlot:'Prépare le prochain import manuel des sorts. Ne modifie rien dans League.'},
};
const en:typeof fr={
 title:'Your settings, easy to find.',intro:'Find an option and adjust it right here.',search:'Search settings',placeholder:'Theme, fewer animations, Flash on F…',clear:'Clear search',categories:'Settings categories',all:'All',app:'Application',league:'League of Legends',result:'setting',results:'settings',recent:'Recently changed',
 empty:'No settings found.',emptyHint:'Try “language”, “animations” or “Flash”.',showAll:'Show all settings',dark:'Dark',light:'Light',enabled:'Enabled',disabled:'Disabled',unset:'Not set',undo:'Undo',undoLabel:'Undo the last change',changed:'Last change',saved:'Settings saved on this device.',storage:'Changes kept for this session. Local saving failed.',retry:'Retry saving',reduced:'Your system reduces motion: this preference takes priority.',
 nativeEnabled:'Enabled',nativeDisabled:'Disabled',unknown:'Unknown state',desktopOnly:'Available in the desktop application.',trayUnavailable:'System tray unavailable. Closing exits the application.',nativeUnknown:'The automatic startup setting could not be read.',nativePending:'Checking the setting…',nativeFailed:'The system setting could not be confirmed.',nativeStorage:'System preferences could not be read. Change the closing behavior to save them again.',localeFailed:'The system menu language could not be synchronized.',nativeRetry:'Reload system settings',localeRetry:'Synchronize menu',
 names:{autoRunes:'Import runes',autoItems:'Import items',autoMinGames:'Minimum games',autoCustomRole:'Role in custom games',closeToTray:'Close to background',autostartEnabled:'Launch at login',theme:'Theme',locale:'Language',motion:'Animations',flashSlot:'Flash position'},
 paths:{autoRunes:'League / Imports',autoItems:'League / Imports',autoMinGames:'League / Imports',autoCustomRole:'League / Imports',closeToTray:'Application / Window',autostartEnabled:'Application / Startup',theme:'Application / Appearance',locale:'Application / Language',motion:'Application / Accessibility',flashSlot:'League / Preparation'},
 descriptions:{autoRunes:'On pre-pick, imports the most played page for your role.',autoItems:'On pre-pick, imports the most played set for your role.',autoMinGames:'Games required before a variant can be imported.',autoCustomRole:'Role used when League does not provide one in custom games.',closeToTray:'Keeps the companion running. Quit remains available in the system menu.',autostartEnabled:'Starts the companion when you sign in to your computer.',theme:'Dark or light, whichever feels comfortable.',locale:'Application text changes immediately.',motion:'Transitions and companion movements.',flashSlot:'Prepares the next manual spell import. Does not change anything in League.'},
};
export const settingsCopy={fr,en};
