export const collectionCopy = {
    fr: {
        rarity: 'Rareté', allRarities: 'Toutes les raretés', series: 'Série', allSeries: 'Toutes les séries',
        rarities: {kNoRarity:'Standard', kRare:'Rare', kEpic:'Épique', kLegendary:'Légendaire', kMythic:'Mythique', kUltimate:'Ultime', kExalted:'Exalté', kTranscendent:'Transcendant'},
        title: 'Collection', search: 'Rechercher un skin, un champion, une rareté, une série…', champion: 'Champion', allChampions: 'Tous les champions',
        filters: {all: 'Tous', owned: 'Possédés', missing: 'Manquants', wishes: 'Souhaits'},
        owned: 'possédés', skins: 'skins', temporary: 'temporaires', unknown: 'possession inconnue',
        ownership: {owned: 'Possédé', missing: 'Non possédé', temporary: 'Temporaire', unknown: 'Possession inconnue'},
        status: {disconnected: 'Connecte League pour charger ta collection.', loading: 'Chargement de la collection…', unavailable: 'Collection indisponible. Réessaie lorsque le client est connecté.', ready: 'Aucun skin transmis par le client.'},
        source: 'Client League', cached: 'Dernière collection · hors connexion', staleConnected: 'Dernière collection · actualisation en attente', stale: 'Dernière collection conservée. Les souhaits restent en lecture seule jusqu’à sa prochaine actualisation.',
        empty: 'Aucun skin pour ces filtres.', reset: 'Réinitialiser', refresh: 'Actualiser la collection', close: 'Fermer la fiche du skin',
        addWish: 'Ajouter aux souhaits', removeWish: 'Retirer des souhaits', saving: 'Enregistrement…', wish: 'Dans les souhaits',
        storageError: 'Les souhaits locaux ne sont pas disponibles. Actualise avant de les modifier.',
        errors: {connection: 'Connexion à la collection indisponible.', refresh: 'Impossible d’actualiser la collection.', wish: 'Le souhait n’a pas été enregistré. Actualise puis réessaie.'},
        imageUnavailable: 'Visuel indisponible',
        showMore: 'Afficher plus', count: 'Résultats', results: 'résultats', wishHint: 'Souhait enregistré sur cet appareil pour ce compte.',
    },
    en: {
        rarity: 'Rarity', allRarities: 'All rarities', series: 'Series', allSeries: 'All series',
        rarities: {kNoRarity:'Standard', kRare:'Rare', kEpic:'Epic', kLegendary:'Legendary', kMythic:'Mythic', kUltimate:'Ultimate', kExalted:'Exalted', kTranscendent:'Transcendent'},
        title: 'Collection', search: 'Search a skin, champion, rarity, series…', champion: 'Champion', allChampions: 'All champions',
        filters: {all: 'All', owned: 'Owned', missing: 'Missing', wishes: 'Wishlist'},
        owned: 'owned', skins: 'skins', temporary: 'temporary', unknown: 'unknown ownership',
        ownership: {owned: 'Owned', missing: 'Not owned', temporary: 'Temporary', unknown: 'Ownership unknown'},
        status: {disconnected: 'Connect League to load your collection.', loading: 'Loading collection…', unavailable: 'Collection unavailable. Try again when the client is connected.', ready: 'The client returned no skins.'},
        source: 'League client', cached: 'Last collection · offline', staleConnected: 'Last collection · awaiting refresh', stale: 'Last collection retained. Your wishlist is read-only until the collection is refreshed.',
        empty: 'No skins match these filters.', reset: 'Reset filters', refresh: 'Refresh collection', close: 'Close skin details',
        addWish: 'Add to wishlist', removeWish: 'Remove from wishlist', saving: 'Saving…', wish: 'In wishlist',
        storageError: 'Local wishes are unavailable. Refresh before editing them.',
        errors: {connection: 'Collection connection unavailable.', refresh: 'Could not refresh the collection.', wish: 'The wish was not saved. Refresh and try again.'},
        imageUnavailable: 'Artwork unavailable',
        showMore: 'Show more', count: 'Results', results: 'results', wishHint: 'Wishlist saved on this device for this account.',
    },
} as const;
