import {useEffect,useState} from "react";
import {assets} from "./fixtures";
import {draftCopy} from "./draftCopy";
import {suggestions,teams,type DraftAction,type DraftState} from "./draft";
import type {Locale} from "./model";
import {Icon,Flame} from "./Icon";
import {RuneTrees} from "./RuneTrees";
import labels from "../../public/prototype/assets/draft-labels.json";

export function DraftPage({state,locale,dispatch,onHome,playing,onPlaying}:{state:DraftState;locale:Locale;dispatch:(action:DraftAction)=>void;onHome:()=>void;playing:boolean;onPlaying:(value:boolean)=>void}){
 const t=draftCopy[locale],names=labels[locale];
 const [autoImport,setAutoImport]=useState(false),[imported,setImported]=useState(false);
 const locked=state.stage>=4,loading=state.stage===5,live=state.stage===6;
 useEffect(()=>{setImported(autoImport&&state.stage>=4);},[state.preview,state.stage,autoImport]);
 const roster=teams(state);
 const action=(a:DraftAction)=>{onPlaying(false);dispatch(a);};
 const items=(ids:number[],ordered=false)=>{const List=ordered?"ol":"ul";return <List role="list" className={`draft-items ${ordered?"item-progression":""}`}>{ids.map((id,i)=>{const name=names.items[String(id) as keyof typeof names.items];return <li key={`${id}-${i}`}><span className="item-picture"><img src={`${assets}${id}.png`} alt="" title={name} width="40" height="40"/>{ordered&&<b aria-hidden="true">{i+1}</b>}</span><span className="item-name">{name}</span></li>;})}</List>;};
 const plan=<div className="draft-plan"><div className="plan-heading"><span className="caption">{t.synergy}</span><strong><Icon name="users" size={15}/>{state.stage>=2?t.frontBack:t.engage}</strong></div><div className="scaling-summary"><span className="caption">{t.scaling}</span><div className="power-curve" role="img" aria-label={`${t.early} → ${t.late} · ${t.simulation}`}><i style={{height:"28%"}}/><i style={{height:"45%"}}/><i style={{height:state.stage>=2?"85%":"62%"}}/><i style={{height:"94%"}}/></div><div className="power-labels"><span>{t.early}</span><span>{t.mid}</span><span>{t.late}</span></div></div></div>;
 return <main className={`draft-page ${locked?"is-locked":""}`}>
  <div className="draft-heading"><div><span className="caption">{t.pool}</span><h1>{live?t.live:loading?t.loading:locked?t.preparing:t.draft}</h1></div><button className="outline-button" onClick={onHome}>{t.home}</button></div>
  <div className="draft-demo-controls"><span className="demo-tag">{t.simulation}</span><div><button className="text-button" aria-pressed={playing} onClick={()=>onPlaying(!playing)} disabled={state.stage===6||!playing&&state.stage===3&&!state.prepick}>{playing?t.pause:t.play}</button><button className="outline-button" disabled={state.stage===6||state.stage===3&&!state.prepick} onClick={()=>action({type:"next"})}>{t.next}</button><button className="icon-button" title={t.restart} aria-label={t.restart} onClick={()=>action({type:"reset"})}><Icon name="replay" size={18}/></button><button className="text-button" onClick={()=>action({type:"side"})}>{state.side==="blue"?t.blue:t.red}</button></div></div>
  {state.stage===3&&!state.prepick&&<p className="draft-missing-pick" role="status">{t.noPick}</p>}
  <div className="draft-timeline" aria-label={t.mode}>{t.steps.map((label,i)=><span className={i===state.stage?"current":i<state.stage?"done":""} aria-current={i===state.stage?"step":undefined} key={label}><i/>{label}</span>)}</div>
  {loading?<section className="draft-loading panel" key="loading"><Flame size={60}/><h2>{state.prepick}</h2><p>{t.loadingHint}</p><div className="loading-team">{[...roster.blue,...roster.red].map((name,i)=><img key={i} src={`${assets}${name??"Ahri"}.png`} alt={name??t.waiting}/>)}</div><button className="primary-button" onClick={()=>action({type:"next"})}>{t.openGame}</button></section>:live?<section className="live-prototype panel" key="live"><span className="caption">{t.gameNote}</span><div className="live-hero"><img src={`${assets}${state.prepick}.png`} alt={state.prepick??""}/><div><h2>{state.prepick}</h2><p>08:36 · {t.roles[2]}</p></div></div><div className="live-cues">{[[t.gold,t.goldValue],[t.objective,t.objectiveValue],[t.strength,t.strengthValue]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><p className="small-muted">{t.liveNote}</p></section>:<>
  <div className="draft-rosters">{(["blue","red"] as const).map(side=><section key={side} className={`panel team-roster ${side}`} aria-label={side==="blue"?t.blue:t.red}><header><strong>{side===state.side?t.ours:t.theirs}</strong><span>{side==="blue"?`${t.blue} · ${t.first}`:t.red}</span></header><div className="team-portraits">{roster[side].map((name,i)=>{
   const self=i===2&&side===state.side;
   const champion=name??(self?state.prepick:null);
   return <div key={i} className={`champion-card ${self?"self-slot":""} ${!name&&champion?"is-prepick":""}`}>
    {champion?<img className="champion-card-art" src={`${assets}${champion}-card.jpg`} alt=""/>:<span className="unpicked-symbol" aria-hidden="true">◇</span>}
    <small className="champion-card-role">{t.roles[i]}</small>
    <div className="champion-card-caption"><strong>{champion==="LeeSin"?"Lee Sin":champion??t.waiting}</strong>{self&&<span>{t.you}{!locked&&champion?` · ${t.steps[0]}`:""}</span>}</div>
   </div>;
  })}</div><div className="ban-line"><span>{t.bans}</span>{state.stage>=1&&side==="blue"?<><img src={`${assets}Lux.png`} alt="Lux"/><span>Lux</span></>:<span>—</span>}</div></section>)}</div>
  <div className="draft-workspace">
   <div className="suggestion-collapse" aria-hidden={locked} inert={locked}><section className="panel suggestion-panel"><header><span className="caption">{t.pool}</span><h2>{t.suggested}</h2></header><div key={state.stage} className="suggestion-list">{suggestions(state).map((name,i)=><button key={name} className={state.preview===name?"selected":""} aria-pressed={state.preview===name} onClick={()=>action({type:"preview",champion:name})}><img className="suggestion-art" src={`${assets}${name}-splash.jpg`} alt=""/><span><strong>{name}</strong><small>{name==="Ahri"?t.reasons[0]:name==="Orianna"?t.reasons[1]:t.reasons[2]}</small></span><span className="pick-order">{i+1}</span></button>)}</div>{plan}</section></div>
   <section className="panel champion-preparation"><div className="draft-champion-art" style={{backgroundImage:`url('${assets}${state.preview}-splash.jpg')`}}/><div className="draft-champion-header"><span className="caption">{locked?t.locked:t.preview}</span><h2>{state.preview}</h2><span className="matchup-chip">{state.stage>=2&&<img src={`${assets}Yasuo.png`} alt=""/>}<span><small>{t.matchup}</small><strong>{state.stage>=2?"Yasuo":t.waiting}</strong></span></span>{!locked&&state.prepick&&state.preview!==state.prepick&&<button className="return-prepick" onClick={()=>action({type:"return"})}><Icon name="replay" size={13}/>{t.returnPick} · {state.prepick}</button>}</div><div className="preparation-body" key={`${state.preview}-${state.stage>=2}`}><div className="rune-heading"><h3>{t.runes}</h3><span>{state.stage>=2?t.adaptive:t.generic}</span></div><RuneTrees champion={state.preview} stage={state.stage} locale={locale}/><p className="small-muted">{t.runeNote}</p>{!locked?<div className="draft-pick-actions"><button className="outline-button" onClick={()=>action({type:"prepick",champion:state.preview})} aria-pressed={state.prepick===state.preview}>{t.prepick}</button><button className="primary-button" disabled={!state.prepick||state.stage<3} title={state.stage<3?t.waitTurn:undefined} onClick={()=>action({type:"lock"})}>{t.lock}</button></div>:<div className="locked-preparation"><p className="locked-note"><Icon name="check" size={17}/>{t.locked}</p>{plan}</div>}</div></section>
   <section className="panel draft-build"><header><span className="caption">{t.preparing}</span><h2>{t.build}</h2></header><div className="build-groups" key={`${state.preview}-${state.stage>=2}`}><section><h3>{t.start}</h3>{items([1056,2003])}</section><section className="core-build"><h3>{t.core}</h3>{items(state.stage>=2?[6655,3020,3157,3089,3135]:[6655,3020,3118,3089,3135],true)}</section><section className="situational-build"><h3>{t.situational}</h3>{items([3157,3135])}</section><section className="utility-build"><h3>{t.utility}</h3>{items([1026,2055,3364,1083])}</section></div><div className="import-controls"><label><input type="checkbox" checked={autoImport} onChange={e=>setAutoImport(e.target.checked)}/>{t.auto}</label><button className="outline-button" onClick={()=>setImported(true)}>{t.import}</button><span role="status">{imported?t.imported:""}</span></div></section>
  </div>
  </>}
 </main>;
}
