const fr={
 primaryTree:"Principale",secondaryTree:"Secondaire",runeSelected:"Sélectionnée",runeAlternative:"Alternative",
 waitTurn:"Disponible à votre tour · étape Composition complète",draft:"Sélection des champions",loading:"La Faille vous attend",live:"En partie",preparing:"Préparation",blue:"Côté bleu",red:"Côté rouge",first:"Premier pick",ours:"Votre équipe",theirs:"Adversaires",you:"Vous",waiting:"À sélectionner",bans:"Bans",suggested:"Pour cette composition",pool:"Votre pool · Mid",preview:"Aperçu",returnPick:"Revenir au prépick",prepick:"Prépick · simulation",lock:"Verrouiller · simulation",locked:"Champion verrouillé",synergy:"Plan de jeu",frontBack:"Front to back",engage:"Engage & contrôle",early:"Début",mid:"Milieu",late:"Fin",scaling:"Courbe de puissance",runes:"Runes",build:"Objets",matchup:"Matchup",generic:"Polyvalent",adaptive:"Contre Yasuo",start:"Départ",core:"Progression du build",situational:"Options situationnelles",utility:"Utilitaires & composants",import:"Simuler l’import",imported:"Import simulé · aucune action dans LoL",auto:"Import automatique · simulation",ready:"Préparation terminée",openGame:"Entrer en partie · simulation",home:"Retour à l’accueil",next:"Étape suivante",restart:"Recommencer",play:"Lecture automatique",pause:"Pause",side:"Changer de côté",simulate:"Lancer la démo draft",entering:"Draft détectée · simulation",steps:["Votre prépick","Lux bannie","Yasuo sélectionné","Composition complète","Champion verrouillé","Chargement","En partie"],
 reasons:["Votre champion familier","Contrôle de zone","Prise en main accessible"],
 simulation:"Scénario illustratif · recommandations et timings fictifs",draftChanged:"Composition actualisée",gameNote:"Vue de l’application · aucun overlay superposé au jeu",gold:"Écart d’or",goldValue:"+320",objective:"Prochain objectif",objectiveValue:"Dragon · 1:24",strength:"Votre fenêtre",strengthValue:"Niveau 6",liveNote:"Repères fictifs pour tester l’arrivée en partie. L’analyse et le suivi réels restent à développer.",layout:"Maquettes de layout",figma:"Ouvrir dans Figma",gallery:"Référence de conception",galleryHint:"Copie des wireframes du 30 septembre 2026. La structure et les décisions restent consultables ; le style évolue dans le prototype.",galleryBack:"Retour au prototype",loadingHint:"Transition simulée vers la vue en partie",lockHint:"Les recommandations se replient ; votre préparation reste accessible.",roles:["Top","Jungle","Mid","ADC","Support"],noPick:"Choisissez un prépick pour poursuivre",cancel:"Annuler",autoEntry:"Arrivée automatique dans un instant…",mode:"Démo en cours",credits:"Illustrations Riot Games · données fictives",runeNote:"Arbres illustratifs · build non validé",situationLabel:"Résistance / pénétration",adaptiveNote:"Le scénario change la préparation quand le matchup est révélé."
};
const en:typeof fr={
 primaryTree:"Primary",secondaryTree:"Secondary",runeSelected:"Selected",runeAlternative:"Alternative",
 waitTurn:"Available on your turn · Full composition step",draft:"Champion select",loading:"The Rift awaits",live:"In game",preparing:"Preparation",blue:"Blue side",red:"Red side",first:"First pick",ours:"Your team",theirs:"Opponents",you:"You",waiting:"Not selected",bans:"Bans",suggested:"For this composition",pool:"Your pool · Mid",preview:"Preview",returnPick:"Back to prepick",prepick:"Prepick · simulation",lock:"Lock in · simulation",locked:"Champion locked",synergy:"Game plan",frontBack:"Front to back",engage:"Engage & control",early:"Early",mid:"Mid",late:"Late",scaling:"Power curve",runes:"Runes",build:"Items",matchup:"Matchup",generic:"General",adaptive:"Against Yasuo",start:"Starting items",core:"Build path",situational:"Situational options",utility:"Utility & components",import:"Simulate import",imported:"Import simulated · no action in LoL",auto:"Automatic import · simulation",ready:"Preparation complete",openGame:"Enter game · simulation",home:"Back home",next:"Next step",restart:"Restart",play:"Auto play",pause:"Pause",side:"Switch side",simulate:"Start draft demo",entering:"Draft detected · simulation",steps:["Your prepick","Lux banned","Yasuo selected","Full composition","Champion locked","Loading","In game"],
 reasons:["Your familiar champion","Zone control","Easy to pick up"],
 simulation:"Illustrative scenario · fictional recommendations and timings",draftChanged:"Composition updated",gameNote:"Application view · no in-game overlay",gold:"Gold difference",goldValue:"+320",objective:"Next objective",objectiveValue:"Dragon · 1:24",strength:"Your window",strengthValue:"Level 6",liveNote:"Fictional cues to test the transition into game. Real analysis and tracking are not implemented.",layout:"Layout mockups",figma:"Open in Figma",gallery:"Design reference",galleryHint:"Wireframe snapshot from September 30, 2026. Structure and decisions remain available while the prototype style evolves.",galleryBack:"Back to prototype",loadingHint:"Simulated transition to the in-game view",lockHint:"Recommendations fold away; your preparation stays available.",roles:["Top","Jungle","Mid","ADC","Support"],noPick:"Choose a prepick to continue",cancel:"Cancel",autoEntry:"Entering draft shortly…",mode:"Demo running",credits:"Riot Games artwork · fictional data",runeNote:"Illustrative trees · unvalidated build",situationLabel:"Resistance / penetration",adaptiveNote:"The scenario updates preparation when the matchup is revealed."
};
export const draftCopy={fr,en};
export const figmaLayout="https://www.figma.com/design/k4SI8lmJungFY3qhYP8ax0?node-id=74-63";
